services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: laravel0-app
    restart: unless-stopped
    # env_file:
      # - .env
    # user: "1000:1000" # For Permission, Only for production
    volumes:
      - ./src:/var/www/html
      # - ./.env:/var/www/html/.env
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel0-network
    # command: bash -c "php artisan horizon"
    # command: bash -c "php artisan queue:work --sleep=3 --tries=3 --timeout=90"
    depends_on:
      - mariadb

  webserver:
    image: nginx:alpine
    container_name: laravel0-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8001:443" #in production 443:443
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - laravel0-network

  mariadb:
    image: mariadb:10.11
    container_name: laravel0-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - laravel0-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel0-network

  redis:
    image: redis:alpine
    container_name: laravel0-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel0-network

networks:
  laravel0-network:
    driver: bridge

volumes:
  laravel0-data:
    driver: local
